cast = ["Clease", "Palin", "Jones", "Idle"]
print(cast)
print(len(cast))
print(cast[1])
cast.append("Gilliam")
print(cast)
cast.pop()
print(cast)
cast.extend(["Gilliam", "Chapman"])
print(cast)
cast.remove("Chapman")
print(cast)
cast.insert(4,"Chapman")
print(cast)
cast.insert(6,"index")
print(cast)
cast.insert(10,"heheh")
print(cast)
print(len(cast))
